# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

def commonPods
  
end

target 'LynxMail' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!
  commonPods
  # Pods for LynxMail

end
