# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

def commonPods
  
end

target 'LynxMail' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!
  commonPods
  # Pods for LynxMail

  pod 'react-native-config', :path => '../node_modules/react-native-config'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

end
